# Generated by Django 3.0.5 on 2020-04-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200418_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilepic',
            field=models.ImageField(blank=True, default='profiledefault.jpeg', null=True, upload_to=''),
        ),
    ]
